// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjowwycfhxizwajkohwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqb3d3eWNmaHhpendhamtvaHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzczODksImV4cCI6MjA2OTcxMzM4OX0.EXcqZpdINI6wW5uK1uXipoFi8oXKzX0CccVBTbKdteY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});